# база данных Postgresql
version: "3"
services:
  db:
    image: postgres:13
    ports:
      - 80:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: name_db

volumes:
  postgres_data: